server:
  port: 8082

spring:
  application:
    name: movie-service
  # Configuration Neo4j
  neo4j:
    uri: ${NEO4J_URI:bolt://vps-77043236.vps.ovh.ca:7687/}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:Neo4j2022}
  data:
    neo4j:
      database: neo4j
  # Configuration sécurité OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keykloak.freeddns.org/realms/neo4flix

# Configuration TMDb API
tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    access-token: ${TMDB_ACCESS_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1OTQxYzc0YmMyMmQ4MTUyMGQ0MTE2ZjViZWJlYWMxNiIsIm5iZiI6MTc2NzQzODEyMS44NjUsInN1YiI6IjY5NThmNzI5M2M3MzRiZGU3N2MzOWQ5ZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.LGtRI0hfH_02j1rV6mA2W3Fa18QqdOlbj_11uGmU4B0}
    image-base-url: https://image.tmdb.org/t/p

# Configuration Feign
spring.cloud.openfeign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic

# Logging
logging:
  level:
    org.springframework.data.neo4j: DEBUG
    sn.dev.movie_service.clients: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always