server:
  port: 8084

spring:
  application:
    name: rating-service
  # Configuration Neo4j
  neo4j:
    uri: ${NEO4J_URI:bolt://vps-77043236.vps.ovh.ca:7687/}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:Neo4j2022}
  data:
    neo4j:
      database: neo4j
  # Configuration sécurité OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak4flix.duckdns.org/realms/neo4flix

movie:
  service:
    url: ${MOVIE_SERVICE_URL:http://localhost:8082}

# Configuration Feign
spring.cloud.openfeign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000

# Logging
logging:
  level:
    org.springframework.data.neo4j: DEBUG