### Variables de base
@baseUrl = http://localhost:8082/api/movies/

### Récupérer tous les films
GET {{baseUrl}}

### Récupérer un film par ID
@id = ddaa11cb-62bc-4d20-9722-7cef5e3f36ae
GET {{baseUrl}}{{id}}


### Créer un nouveau film (Inception)
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Inception",
  "description": "Un voleur qui subtilise des secrets par le biais du rêve.",
  "releaseYear": 2010,
  "genres": [
    {"name": "Action"},
    {"name": "Sci-Fi"}
  ]
}