### Variables de base
@baseUrl = http://localhost:8082/api/movies/

### Récupérer un film par ID
@id = 641fc921-f7bf-45d7-83b9-dd8069f22b96
GET {{baseUrl}}{{id}}


### Créer un nouveau film (Inception)
POST {{baseUrl}}
Content-Type: application/json

{
  "title": "Inception",
  "description": "Un voleur qui subtilise des secrets par le biais du rêve.",
  "releaseYear": 2010,
  "genres": [
    {"name": "Action"},
    {"name": "Sci-Fi"}
  ]
}