@baseUrl=http://localhost:5050
@baseUrlMovies = http://localhost:5050/api/movies/
@token = {{loginKeycloak.response.body.access_token}}
@token = {{refreshTokenKeycloak.response.body.access_token}}
@refreshToken = {{loginKeycloak.response.body.refresh_token}}
@id = 8a6271a9-5bea-4045-aca6-ae0002e75550
@idMovie = 641fc921-f7bf-45d7-83b9-dd8069f22b96

### Récupérer l'utilisateur 1
GET {{baseUrl}}/api/users/me
Authorization: Bearer {{token}}

### 1. Récupérer un Token (Simule le login Angular) avec Keycloak
# @name loginKeycloak
POST http://keycloak4flix.duckdns.org/realms/neo4flix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=neo4flix-app&username=mamadbah&password=password123

###
# @name refreshTokenKeycloak
POST http://keycloak4flix.duckdns.org/realms/neo4flix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=neo4flix-app&refresh_token={{refreshToken}}

### 2. Envoyer la note avec le Token récupéré
POST {{baseUrl}}/api/rates/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "movieId": "641fc921-f7bf-45d7-83b9-dd8069f22b96",
  "score": 8
}

### Recuperer les films
GET {{baseUrl}}/api/movies/
Authorization: Bearer {{token}}

### Récupérer un film par ID
GET {{baseUrl}}/api/movies/{{id}}
Authorization: Bearer {{token}}


### Créer un nouveau film (Inception)
POST {{baseUrl}}/api/movies/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Inception",
  "description": "Un voleur qui subtilise des secrets par le biais du rêve.",
  "releaseYear": 2010,
  "genres": [
    {"name": "Action"},
    {"name": "Sci-Fi"}
  ]
}

### Obtenir mes recommandations
GET {{baseUrl}}/api/recommendations/
Authorization: Bearer {{token}}


### Obtenir mes recommandations
GET {{baseUrl}}/api/movies/recommendations/genre-based
Authorization: Bearer {{token}}

### Obtenir mes recommandations
GET {{baseUrl}}/api/movies/recommendations/collaborative
Authorization: Bearer {{token}}

### test api gateway
GET {{baseUrl}}/poto
# Authorization: Bearer {{token}}

### Récupérer la watchlist de l'utilisateur
GET {{baseUrl}}/api/users/watchlist
Authorization: Bearer {{token}}

### Ajouter un film à la watchlist
POST {{baseUrl}}/api/users/watchlist/{{idMovie}}
Authorization: Bearer {{token}}

### Supprimer un film de la watchlist
DELETE {{baseUrl}}/api/users/watchlist/{{id}}
Authorization: Bearer {{token}}

### Suivre un utilisateur
POST {{baseUrl}}/api/users/follow/{{id}}
Authorization: Bearer {{token}}

### Ne plus suivre un utilisateur
DELETE {{baseUrl}}/api/users/follow/{{id}}
Authorization: Bearer {{token}}

### Liste des abonnements (utilisateurs suivis)
GET {{baseUrl}}/api/users/following
Authorization: Bearer {{token}}

### Liste des abonnés
GET {{baseUrl}}/api/users/followers
Authorization: Bearer {{token}}

### Vérifier si on suit un utilisateur
GET {{baseUrl}}/api/users/following/{{id}}
Authorization: Bearer {{token}}