server:
  port: 5050

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Activation du relais de token pour que le Gateway passe le JWT aux services
      default-filters:
        - TokenRelay

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak4flix.duckdns.org/realms/neo4flix
          jwk-set-uri: http://keycloak4flix.duckdns.org/realms/neo4flix/protocol/openid-connect/certs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG