@baseUrl=http://localhost:8081/api/users/

### Créer un utilisateur (Simule un retour de Keycloak)
POST {{baseUrl}}
Content-Type: application/json

{
  "keycloakId": "user_12345",
  "username": "Mamadou",
  "email": "mamadou@example.com"
}

### Récupérer l'utilisateur
GET {{baseUrl}}me
Authorization: Bearer {{token}}

### 1. Récupérer un Token (Simule le login Angular) avec Keycloak
# @name loginKeycloak
POST http://keycloak4flix.duckdns.org/realms/neo4flix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=neo4flix-app&username=mamadbah&password=password123

###
# @name refreshTokenKeycloak
POST http://keycloak4flix.duckdns.org/realms/neo4flix/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&client_id=neo4flix-app&refresh_token={{refreshToken}}

###
@token = {{loginKeycloak.response.body.access_token}}
@refreshToken = {{loginKeycloak.response.body.refresh_token}}

### 2. Envoyer la note avec le Token récupéré
POST http://localhost:8084/api/rates/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "movieId": "d2264670-b225-4872-8db5-07807d0a43c0",
  "score": 5
}